import { ArrowDown } from 'lucide-react'
import { motion } from 'framer-motion'
import { layers } from '../data/got'

export default function Architecture() {
  return <section id="architecture" className="bg-[#071426] py-24 text-white sm:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="max-w-3xl"><p className="font-bold text-blue-400">CLEAR BY DESIGN</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">A solid architecture for real projects.</h2><p className="mt-5 text-lg leading-8 text-slate-400">Each concern has a home. Follow a request from route to database without untangling a monolith.</p></div>
    <div className="mt-14 grid gap-8 lg:grid-cols-[.85fr_1.15fr]"> <div className="rounded-3xl border border-white/10 bg-white/5 p-6 sm:p-8">{layers.map((l, i) => <div key={l.name}><motion.div initial={{ opacity: .45, scale: .98 }} whileInView={{ opacity: 1, scale: 1 }} whileHover={{ scale: 1.025, x: 4 }} viewport={{ once: true }} transition={{ delay: i * .08 }} className="cursor-default rounded-xl p-3 text-center font-bold text-ink shadow-sm" style={{background:l.color}}>{l.name}</motion.div>{i < layers.length - 1 && <div className="relative mx-auto my-1.5 h-5 w-5"><ArrowDown size={18} className="absolute text-blue-400"/><motion.span className="absolute left-[8px] top-0 size-1.5 rounded-full bg-white shadow-[0_0_8px_#fff]" animate={{y:[0,13,0],opacity:[0,1,0]}} transition={{duration:1.25,repeat:Infinity,delay:i*.16}}/></div>}</div>)}</div>
    <div className="overflow-hidden rounded-3xl border border-white/10 bg-[#0c1b30] p-6 font-mono text-sm sm:p-8"><p className="mb-6 text-xs font-bold tracking-widest text-blue-400">GENERATED SERVICE</p><div className="space-y-2 text-slate-300"><p className="text-white">service/</p><p>├── <span className="text-blue-300">entity/</span></p><p>├── <span className="text-violet-300">repository/</span></p><p>├── <span className="text-emerald-300">service/</span></p><p>├── <span className="text-amber-300">handler/</span></p><p>├── <span className="text-rose-300">route/</span></p><p>├── Dockerfile</p><p>├── go.mod</p><p>└── main.go</p></div><p className="mt-8 border-t border-white/10 pt-6 font-sans leading-7 text-slate-400">The exact generated tree follows the architecture and options selected during setup.</p></div></div>
  </div></section>
}
