import { ArrowDown, Database, ScanSearch, TerminalSquare, Zap } from 'lucide-react'
import { motion } from 'framer-motion'

const flow = [{ icon: Database, text: 'Existing database' }, { icon: ScanSearch, text: 'Schema inspection' }, { icon: TerminalSquare, text: 'GOT CLI' }]
export default function DatabaseToAPI() {
  return <section className="py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid items-center gap-14 lg:grid-cols-2">
    <div><p className="font-bold text-brand">FROM DATA TO ENDPOINTS</p><h2 className="mt-3 text-4xl font-black tracking-tight text-ink sm:text-5xl">Database → Go API</h2><p className="mt-5 max-w-xl text-lg leading-8">Inspect an existing PostgreSQL or SQL Server schema and generate entity, repository, service, handler, and route layers.</p><div className="mt-7 rounded-2xl border border-blue-200 bg-blue-50 p-5"><p className="text-xs font-bold tracking-widest text-blue-700">RUN INSIDE A GENERATED SERVICE</p><code className="mt-2 block font-mono font-bold text-ink">$ got generate crud</code><p className="mt-2 text-sm">Schema inspection is read-only. The database password is collected through a masked prompt.</p></div></div>
    <div className="rounded-3xl border border-slate-200 bg-soft p-6 shadow-xl shadow-slate-200/60 sm:p-8">{flow.map(({icon:Icon,text}, i) => <div key={text}><motion.div whileInView={{ scale: [1, 1.02, 1] }} transition={{ delay: i * .15 }} className="flex items-center gap-4 rounded-xl border border-slate-200 bg-white p-4"><span className="grid size-10 place-items-center rounded-lg bg-blue-50 text-brand"><Icon size={20}/></span><b className="text-ink">{text}</b></motion.div><ArrowDown className="mx-auto my-2 text-blue-300"/></div>)}<div className="grid grid-cols-2 gap-2 text-sm sm:grid-cols-3">{['Entity', 'Repository', 'Service', 'Handler', 'Route'].map(x => <div className="rounded-lg border border-blue-100 bg-white p-3 text-center font-semibold text-ink" key={x}>{x}</div>)}</div><ArrowDown className="mx-auto my-2 text-blue-300"/><div className="flex items-center justify-center gap-2 rounded-xl bg-brand p-4 font-bold text-white"><Zap size={19}/> Working REST API</div></div>
  </div></div></section>
}
