import { ArrowRight, Code2, FileText, GitBranch, PencilLine } from 'lucide-react'

const steps = [
  { icon: FileText, label: 'Existing Go Source' },
  { icon: GitBranch, label: 'Go AST' },
  { icon: PencilLine, label: 'Repository' },
  { icon: Code2, label: 'Service, Handler, Route' },
]

export default function HowItWorks() {
  return (
    <section id="docs" className="bg-slate-950 py-24 text-white sm:py-28">
      <div className="mx-auto max-w-7xl px-5 lg:px-8">
        <div className="max-w-3xl">
          <p className="text-xs font-bold tracking-[0.18em] text-sky-300 uppercase">Extend existing code</p>
          <h2 className="mt-4 text-4xl font-black tracking-[-0.06em] text-white sm:text-5xl">
            Generated by GOT. Owned by you.
          </h2>
        </div>

        <div className="mt-12 rounded-[2rem] border border-white/10 bg-white/5 p-6 sm:p-8">
          <div className="grid gap-4 md:grid-cols-4">
            {steps.map(({ icon: Icon, label }, index) => (
              <div key={label} className="rounded-[1.5rem] border border-white/10 bg-slate-900/80 p-5">
                <div className="flex items-center justify-between">
                  <span className="grid h-10 w-10 place-items-center rounded-xl bg-sky-500/10 text-sky-300">
                    <Icon size={18} />
                  </span>
                  <span className="text-xs font-medium text-slate-400">0{index + 1}</span>
                </div>
                <p className="mt-4 text-lg font-semibold text-white">{label}</p>
                {index < steps.length - 1 && (
                  <div className="mt-5 flex items-center justify-center text-sky-300">
                    <ArrowRight size={18} />
                  </div>
                )}
              </div>
            ))}
          </div>

          <div className="mt-8 rounded-[1.5rem] border border-slate-800 bg-slate-900 p-5 font-mono text-sm text-slate-300">
            <span className="text-sky-300">$</span> got add method --folder orders --name Approve --http-method PATCH --path /:id/approve
          </div>

          <p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">
            GOT updates the relevant source structure instead of replacing files blindly. It understands the application shape and modifies the correct repository, service, handler, and route boundaries.
          </p>
        </div>
      </div>
    </section>
  )
}
