import { ArrowRight, Check, Copy, Sparkles } from 'lucide-react'
import { useState } from 'react'

const commandPreview = 'got api --name users'

export default function ProjectGenerator() {
  const [copied, setCopied] = useState(false)

  const handleCopy = async () => {
    await navigator.clipboard.writeText(commandPreview)
    setCopied(true)
    setTimeout(() => setCopied(false), 1200)
  }

  return (
    <section className="py-24 sm:py-28">
      <div className="mx-auto max-w-7xl px-5 lg:px-8">
        <div className="grid gap-8 rounded-[2rem] border border-slate-200 bg-white/80 p-6 shadow-[0_20px_40px_rgba(15,23,42,0.04)] sm:p-8 lg:grid-cols-[1fr_1.1fr]">
          <div className="flex flex-col justify-between">
            <div>
              <p className="text-xs font-bold tracking-[0.18em] text-sky-700 uppercase">Generate</p>
              <h3 className="mt-4 text-4xl font-black tracking-[-0.06em] text-slate-950 sm:text-5xl">
                Start with the API skeleton. Keep the business logic.
              </h3>
            </div>

            <div className="mt-8 rounded-[1.5rem] border border-slate-200 bg-slate-50 p-5">
              <div className="flex items-center justify-between gap-3">
                <div className="inline-flex items-center gap-2 text-sm font-semibold text-slate-800">
                  <Sparkles size={16} className="text-sky-600" />
                  Command preview
                </div>
                <button aria-label="Copy command" onClick={handleCopy} className="rounded-lg border border-slate-200 bg-white p-2 text-slate-700 hover:border-slate-300">
                  {copied ? <Check size={16} /> : <Copy size={16} />}
                </button>
              </div>

              <code className="mt-4 block rounded-xl border border-slate-200 bg-slate-950 p-3 font-mono text-sm text-sky-300">
                {commandPreview}
              </code>

              <div className="mt-6 flex flex-wrap gap-2 text-sm text-slate-700">
                <span className="rounded-full bg-sky-100 px-2.5 py-1.5 text-sky-700">Entity</span>
                <span className="rounded-full bg-sky-100 px-2.5 py-1.5 text-sky-700">Repository</span>
                <span className="rounded-full bg-sky-100 px-2.5 py-1.5 text-sky-700">Service</span>
                <span className="rounded-full bg-sky-100 px-2.5 py-1.5 text-sky-700">Handler</span>
                <span className="rounded-full bg-sky-100 px-2.5 py-1.5 text-sky-700">Routes</span>
              </div>
            </div>
          </div>

          <div className="rounded-[1.75rem] border border-slate-200 bg-[#0d1726] p-5 text-white sm:p-6">
            <div className="flex items-center justify-between border-b border-white/10 pb-4">
              <div className="flex items-center gap-2 font-mono text-xs uppercase tracking-[0.14em] text-slate-400">
                <span className="h-2.5 w-2.5 rounded-full bg-emerald-400" />
                generated service
              </div>
              <span className="rounded-full border border-emerald-500/30 bg-emerald-500/10 px-2 py-1 text-[10px] font-semibold text-emerald-300">
                ready
              </span>
            </div>

            <div className="mt-6 space-y-2 font-mono text-sm text-slate-300">
              <p>service/</p>
              <p>├── entity/</p>
              <p>├── repository/</p>
              <p>├── service/</p>
              <p>├── handler/</p>
              <p>├── route/</p>
              <p>├── go.mod</p>
              <p>├── main.go</p>
              <p>└── Dockerfile</p>
            </div>

            <div className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-sky-300">
              generated by GOT
              <ArrowRight size={16} />
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
